In [1]:
import torch

In [2]:
item_id2train_graph_id = torch.load('./data/graphs/weighted/item_id2train_graph_id.pt')

In [4]:
item_id2train_graph_id

tensor([    0,     0, 14160, 14161, 14162, 14163, 14164, 14165, 14166, 14167,
        14168, 14169, 14170, 14171, 14172, 14173, 14174, 14175, 14176, 14177,
        14178, 14179, 14180, 14181, 14182, 14183, 14184, 14185, 14186, 14187,
        14188, 14189, 14190, 14191, 14192, 14193, 14194, 14195, 14196, 14197,
        14198, 14199, 14200, 14201, 14202, 14203, 14204, 14205, 14206, 14207,
        14208, 14209, 14210, 14211, 14212, 14213, 14214, 14215, 14216, 14217,
        14218, 14219, 14220, 14221, 14222, 14223, 14224, 14225, 14226, 14227,
        14228, 14229, 14230, 14231, 14232, 14233, 14234, 14235, 14236, 14237,
        14238, 14239, 14240, 14241, 14242, 14243, 14244, 14245, 14246, 14247,
        14248, 14249, 14250, 14251, 14252, 14253, 14254, 14255, 14256, 14257,
        14258, 14259, 14260, 14261, 14262, 14263, 14264, 14265, 14266, 14267,
        14268, 14269, 14270, 14271, 14272, 14273, 14274, 14275, 14276, 14277,
        14278, 14279, 14280, 14281, 14282, 14283, 14284, 14285, 

In [5]:
len(item_id2train_graph_id)

186

In [4]:
item_id2train_graph_id

tensor([    0,     0,     0,  ...,     0,     0, 14343])

In [5]:
unique_elements = item_id2train_graph_id.unique()
unique_elements

tensor([    0, 14160, 14161, 14162, 14163, 14164, 14165, 14166, 14167, 14168,
        14169, 14170, 14171, 14172, 14173, 14174, 14175, 14176, 14177, 14178,
        14179, 14180, 14181, 14182, 14183, 14184, 14185, 14186, 14187, 14188,
        14189, 14190, 14191, 14192, 14193, 14194, 14195, 14196, 14197, 14198,
        14199, 14200, 14201, 14202, 14203, 14204, 14205, 14206, 14207, 14208,
        14209, 14210, 14211, 14212, 14213, 14214, 14215, 14216, 14217, 14218,
        14219, 14220, 14221, 14222, 14223, 14224, 14225, 14226, 14227, 14228,
        14229, 14230, 14231, 14232, 14233, 14234, 14235, 14236, 14237, 14238,
        14239, 14240, 14241, 14242, 14243, 14244, 14245, 14246, 14247, 14248,
        14249, 14250, 14251, 14252, 14253, 14254, 14255, 14256, 14257, 14258,
        14259, 14260, 14261, 14262, 14263, 14264, 14265, 14266, 14267, 14268,
        14269, 14270, 14271, 14272, 14273, 14274, 14275, 14276, 14277, 14278,
        14279, 14280, 14281, 14282, 14283, 14284, 14285, 14286, 

In [6]:
torch.equal(
    item_id2train_graph_id[len(item_id2train_graph_id)-len(unique_elements):],
    unique_elements
)

False

In [11]:
client_id2train_graph_id = torch.load('./data/graphs/weighted/client_id2train_graph_id.pt')

In [12]:
len(client_id2train_graph_id)

99999681

In [13]:
client_id2train_graph_id

tensor([    0,     0,     0,  ...,     0,     0, 14159])

In [10]:
item_id2full_graph_id = torch.load('./data/graphs/weighted/item_id2full_graph_id.pt')

In [11]:
len(item_id2full_graph_id)

185

In [12]:
item_id2full_graph_id

tensor([    0, 15000, 15001, 15002, 15003, 15006, 15007, 15008, 15009, 15010,
        15037, 15014, 15004, 15015, 15005, 15016, 15064, 15017, 15061, 15018,
        15019, 15020, 15110, 15021, 15050, 15038, 15011, 15034, 15022, 15035,
        15036, 15023, 15024, 15039, 15025, 15063, 15040, 15013, 15041, 15074,
        15075, 15088, 15042, 15067, 15051, 15026, 15043, 15065, 15082, 15012,
        15052, 15044, 15076, 15053, 15027, 15090, 15068, 15069, 15028, 15054,
        15077, 15083, 15029, 15078, 15070, 15045, 15091, 15030, 15031, 15032,
        15117, 15079, 15127, 15116, 15033, 15094, 15112, 15106, 15084, 15095,
        15055, 15118, 15080, 15096, 15097, 15056, 15057, 15081, 15058, 15087,
        15123, 15071, 15046, 15126, 15085, 15047, 15062, 15108, 15136, 15111,
        15138, 15101, 15059, 15146, 15130, 15072, 15092, 15066, 15048, 15153,
        15144, 15125, 15139, 15163, 15148, 15102, 15121, 15115, 15098, 15157,
        15093, 15137, 15104, 15113, 15177, 15105, 15124, 15073, 

In [13]:
client_id2full_graph_id = torch.load('./data/graphs/weighted/client_id2full_graph_id.pt')

In [14]:
len(client_id2full_graph_id)

99999681

In [15]:
client_id2full_graph_id

tensor([    0,     0,     0,  ...,     0,     0, 14999])

In [16]:
client_id2full_graph_id.unique()

tensor([    0,     1,     2,  ..., 14997, 14998, 14999])

In [17]:
len(client_id2full_graph_id.unique())

15000

In [17]:
%cd ..

/home/proshian/Documents/my-coles-gnn-experimetns


/home/proshian/.local/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [18]:
from ptls_extension_2024_research.graphs.graph import ClientItemGraph, ClientItemGraphFull


/home/proshian/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


ModuleNotFoundError: No module named '_lzma'

In [ ]:
graph_file_path = 'data/graphs/weighted/train_graph.bin'
client_item_graph = ClientItemGraphFull.from_graph_file(graph_file_path, 'cpu')

In [ ]:
print(client_item_graph.g.nodes())


In [ ]:
len(client_item_graph.g.nodes())


In [12]:
import pandas as pd

In [16]:
df = pd.read_csv('data/transactions.csv')
df.head()

customer_id tr_datetime  mcc_code  tr_type    amount term_id
0     39026145  0 10:23:26      4814     1030  -2245.92     NaN
1     39026145  1 10:19:29      6011     7010  56147.89     NaN
2     39026145  1 10:20:56      4829     2330 -56147.89     NaN
3     39026145  1 10:39:54      5499     1010  -1392.47     NaN
4     39026145  2 15:33:42      5499     1010   -920.83     NaN

In [17]:
df['mcc_code'].unique()

array([4814, 6011, 4829, 5499, 5541, 5200, 5732, 6010, 5331, 5912, 5411,
       5812, 6012, 5719, 5722, 5621, 5814, 5921, 5941, 5691, 5813, 5211,
       4812, 5945, 5983, 5999, 5943, 5533, 6300, 7832, 8099, 5992, 3501,
       6536, 7997, 5641, 4722, 5661, 5651, 7011, 5699, 5942, 7298, 7999,
       5712, 5511, 5422, 5399, 4900, 7538, 5949, 5977, 5948, 5631, 5311,
       5462, 4112, 8999, 8021, 5714, 5251, 4789, 7542, 5947, 3000, 8043,
       5944, 5734, 5611, 5532, 4816, 7311, 5655, 6051, 7994, 5995, 5309,
       5964, 8299, 8244, 4111, 4511, 9399, 5441, 7922, 5261, 7699, 7995,
       7629, 5816, 5735, 5039, 5300, 5199, 4121, 5065, 7399, 7299, 8011,
       7230, 9222, 5946, 5131, 5994, 5231, 8071, 5094, 5047, 5072, 7210,
       5976, 5045, 7932, 4215, 5542, 5099, 5713, 4899, 7933, 5681, 5193,
       1711, 6211, 8398, 5599, 5993, 8062, 5169, 4214, 5733, 5013, 7221,
       5571, 7993, 5971, 5968, 7372, 5074, 5044, 5811, 5111, 8641, 7512,
       7523, 9311, 8220, 7991, 7996, 4784, 5931, 78

In [18]:
len(df['mcc_code'].unique())

184

In [19]:
ptls_train_df = pd.read_parquet('data/train_trx.parquet/')

In [20]:
ptls_train_df.head()

customer_id                                         event_time  \
0    10058778  [23.35869212962963, 23.359502314814815, 36.498...   
1    10230827  [0.25885416666666666, 1.5346412037037038, 1.65...   
2    11681378  [0.3015393518518519, 0.3589583333333333, 0.875...   
3    14123285  [15.489155092592593, 21.68777777777778, 23.612...   
4    16536678  [75.40552083333333, 75.59731481481481, 83.5602...   

                                              amount  \
0  [13.420652589715486, -13.420652589715486, 14.6...   
1  [13.015188216272872, -10.01949835204266, -9.76...   
2  [-8.41023807171957, -7.9242460340479255, -9.91...   
3  [12.792045221523114, 12.216683253401992, -10.7...   
4  [14.336942434053569, -9.326395693771916, -9.32...   

                                            mcc_code  \
0  [2, 6, 3, 2, 2, 3, 2, 3, 2, 6, 6, 3, 10, 3, 2,...   
1  [3, 2, 5, 8, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 3, ...   
2  [4, 7, 2, 2, 11, 5, 7, 6, 2, 7, 7, 3, 6, 7, 7,...   
3  [3, 3, 2, 2, 2, 2, 3, 3, 2, 2, 3, 3, 2, 2, 2, ...   
4  [2, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 4, 4, 4, 4, ...   

                                             tr_type  \
0  [8, 13, 6, 3, 3, 23, 3, 11, 8, 19, 20, 6, 2, 6...   
1  [29, 3, 5, 5, 3, 3, 3, 4, 3, 3, 4, 3, 3, 4, 29...   
2  [4, 2, 27, 28, 2, 5, 2, 13, 3, 2, 2, 9, 13, 2,...   
3  [11, 9, 16, 25, 25, 16, 11, 6, 16, 25, 11, 17,...   
4  [8, 4, 4, 4, 4, 8, 4, 4, 4, 8, 4, 4, 4, 4, 4, ...   

                                             term_id  trx_count  target  
0  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...        142     1.0  
1  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...        279     0.0  
2  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...        881     1.0  
3  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...       1051     0.0  
4  [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...        128     0.0

In [23]:
mcc_ids = {el for arr in ptls_train_df['mcc_code'] for el in arr}

In [25]:
print(mcc_ids)

{2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185}


In [26]:
?df.to_parquet

Signature:
df.to_parquet(
    path: 'FilePath | WriteBuffer[bytes] | None' = None,
    engine: "Literal['auto', 'pyarrow', 'fastparquet']" = 'auto',
    compression: 'str | None' = 'snappy',
    index: 'bool | None' = None,
    partition_cols: 'list[str] | None' = None,
    storage_options: 'StorageOptions | None' = None,
    **kwargs,
) -> 'bytes | None'
Docstring:
Write a DataFrame to the binary parquet format.

This function writes the dataframe as a `parquet file
<https://parquet.apache.org/>`_. You can choose different parquet
backends, and have the option of compression. See
:ref:`the user guide <io.parquet>` for more details.

Parameters
----------
path : str, path object, file-like object, or None, default None
    String, path object (implementing ``os.PathLike[str]``), or file-like
    object implementing a binary ``write()`` function. If None, the result is
    returned as bytes. If a string or path, it will be used as Root Directory
    path when writing a partitioned datas

In [28]:
import pickle

with open('data/train_trx.parquet', 'rb') as f:
    data = pickle.load(f)

In [30]:
type(data)

list

In [31]:
data[0]

{'target': 1,
 'customer_id': 22899,
 'feature_arrays': {'mcc_code': array([ 3,  3,  1,  1,  2,  1,  1,  3,  1,  3,  2,  1,  2,  3,  1,  2,  7,
          8,  3,  1,  1,  1,  1,  3,  3,  2,  7,  2,  1,  3,  1,  2,  5,  5,
          6,  3,  1,  1,  5,  2,  5,  1,  5,  2,  1,  1,  1,  2,  5,  1,  3,
          3,  2,  2,  1,  3,  1,  6,  1,  3,  1,  1,  3,  3,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  3,  1,  3,  6,  1,  5,  2,  1,  3,  3,  4,  1,
          1,  4,  7,  6,  1,  1,  6,  1,  5,  6,  1,  1,  5,  5,  6,  7,  3,
          2,  7,  1,  5,  5, 49,  3,  1,  6,  2,  3,  1,  1,  1,  2,  2,  1,
          2,  1,  1,  1,  5,  3,  1,  7,  7,  6,  3,  2,  1,  1,  1,  3,  1,
          3,  1,  1,  1,  1,  1,  5,  5,  2,  6,  5,  1,  2,  3,  3,  1,  3,
          3,  2,  1,  3,  3,  1,  2,  1,  1,  3,  3,  1,  5,  4,  1,  1,  3,
          1,  1,  5,  5,  1,  3,  3,  3,  2,  6,  1,  1,  3,  6,  1,  3,  1,
          1,  1,  6,  2,  3,  1,  3,  1,  5,  5,  1,  1,  1,  1,  6,  1,  3,
         

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('data/transactions.csv')
df.head()

customer_id tr_datetime  mcc_code  tr_type    amount term_id
0     39026145  0 10:23:26      4814     1030  -2245.92     NaN
1     39026145  1 10:19:29      6011     7010  56147.89     NaN
2     39026145  1 10:20:56      4829     2330 -56147.89     NaN
3     39026145  1 10:39:54      5499     1010  -1392.47     NaN
4     39026145  2 15:33:42      5499     1010   -920.83     NaN

In [39]:
df['mcc_code'].head()

0    4814
1    6011
2    4829
3    5499
4    5499
Name: mcc_code, dtype: int64

In [40]:
item_map = pd.read_csv('data/mcc_code_mapping.csv')
item_map.head()

_orig_mcc_code  mcc_code
0            6011         2
1            6010         3
2            4814         4
3            5411         5
4            4829         6

In [41]:
df = df.rename(columns={'mcc_code': '_orig_mcc_code'})
df['_orig_mcc_code'] = df['_orig_mcc_code'].fillna("#EMPTY")

In [42]:
df = df.merge(item_map, on='_orig_mcc_code', how='left')
df.head()

customer_id tr_datetime  _orig_mcc_code  tr_type    amount term_id  \
0     39026145  0 10:23:26            4814     1030  -2245.92     NaN   
1     39026145  1 10:19:29            6011     7010  56147.89     NaN   
2     39026145  1 10:20:56            4829     2330 -56147.89     NaN   
3     39026145  1 10:39:54            5499     1010  -1392.47     NaN   
4     39026145  2 15:33:42            5499     1010   -920.83     NaN   

   mcc_code  
0         4  
1         2  
2         6  
3         7  
4         7

In [43]:
df = df.drop(columns = ['_orig_mcc_code'])
df.head()

customer_id tr_datetime  tr_type    amount term_id  mcc_code
0     39026145  0 10:23:26     1030  -2245.92     NaN         4
1     39026145  1 10:19:29     7010  56147.89     NaN         2
2     39026145  1 10:20:56     2330 -56147.89     NaN         6
3     39026145  1 10:39:54     1010  -1392.47     NaN         7
4     39026145  2 15:33:42     1010   -920.83     NaN         7